name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: erlef/setup-beam@049962787bb993eed9618052c3096a5c5157205a
        with:
          version-type: strict
          version-file: .tool-versions
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
